version: '3.8'
services:
  node1:
    build: .
    image: ghcr.io/drakkkkk/kvstore:latest
    network_mode: "host"
    command: ["8080", "1"]
  node2:
    build: .
    image: ghcr.io/drakkkkk/kvstore:latest
    network_mode: "host"
    command: ["8081", "2"]
  node3:
    build: .
    image: ghcr.io/drakkkkk/kvstore:latest
    network_mode: "host"
    command: ["8082", "3"]