services:
  node1:
    build: .
    image: ghcr.io/drakkkkk/kvstore:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    command: ["8080", "1"]

  node2:
    image: ghcr.io/drakkkkk/kvstore:latest
    network_mode: "service:node1" # This forces node2 to share node1's localhost
    command: ["8081", "2"]
    depends_on:
      - node1

  node3:
    image: ghcr.io/drakkkkk/kvstore:latest
    network_mode: "service:node1" # This forces node3 to share node1's localhost
    command: ["8082", "3"]
    depends_on:
      - node1